// Put courses you want in this array

module.exports = [
  // "https://www.vuemastery.com/courses/vuex-fundamentals/vuex4-intro-to-vuex",
  // "https://www.vuemastery.com/courses/touring-vue-router/vue-router-introduction",
  // "https://www.vuemastery.com/courses/vue3-typescript/why-vue-&-typescript",
  // "https://www.vuemastery.com/courses/real-world-vue3/rwv3-orientation",
  // "https://www.vuemastery.com/courses/from-vue2-to-vue3/from-vue-2-to-vue-3",
  // "https://www.vuemastery.com/courses/intro-to-vue-3/intro-to-vue3",
  // "https://www.vuemastery.com/courses/vue3-deep-dive-with-evan-you/vue3-overview",
  // "https://www.vuemastery.com/courses/vue3-forms/forms-introduction",
  // "https://www.vuemastery.com/courses/build-a-gmail-clone-with-vue3/tour-the-project",
  // "https://www.vuemastery.com/courses/component-design-Patterns/introduction",
  // "https://www.vuemastery.com/courses/vue-3-reactivity/vue3-reactivity",
  // "https://www.vuemastery.com/courses/unit-testing/what-to-test",
  // "https://www.vuemastery.com/courses/vue-3-essentials/why-the-composition-api",
  // "https://www.vuemastery.com/courses/animating-vue/why-animate",
  // "https://www.vuemastery.com/courses/beautify-with-vuetify/getting-started-with-vuetify",
  // "https://www.vuemastery.com/courses/watch-us-build-trello-clone/tour-of-the-app",
  // "https://www.vuemastery.com/courses/token-based-authentication/intro-to-authentication",
  // "https://www.vuemastery.com/courses/next-level-vue/next-level-vue-orientation",
  // "https://www.vuemastery.com/courses/mastering-vuex/intro-to-vuex",
  // "https://www.vuemastery.com/courses/scaling-vue-with-nuxt-js/why-use-nuxt",
  // "https://www.vuemastery.com/courses/real-world-vue-js/real-world-intro",
  // "https://www.vuemastery.com/courses/advanced-components/the-introduction",
  // "https://www.vuemastery.com/courses/intro-to-vue-js/vue-instance",
];
